Added support for watchlist, removed wrong assertion from ccl_rewrite.c (wrongified by the chane in the main loop), removed printing of subsumption steps from subsumption code (its now the obligation of the caller to do so). Added support for watch lists, got rid of DemodInsert() (now better named functions in ccl_clausesets.c). Added priofuns for the watch list. Added Built-in heuristic using watch list. Added support for watch list subsumer extraction. Added support for the watch list.

diff --git a/PROVER/eproof b/PROVER/eproof
--- a/PROVER/eproof
+++ b/PROVER/eproof
@@ -68,7 +68,7 @@ for argument in  $*; do
 done
 
 $EXECPATH/eprover $newargs -l4 -R -o- --pcl-terms-compressed --pcl-compact> $tmpfile
-tail -50 $tmpfile > $tmpfile2
+tail -60 $tmpfile > $tmpfile2
 searchtime=`cat $tmpfile2|grep "Total time"|cut -d: -f2|sed -e's/[s ]//g'|cut -d. -f1`
 if [ "$searchtime" ]; then
     statusline=`grep -c 'No proof found!' $tmpfile2`
@@ -79,8 +79,13 @@ if [ "$searchtime" ]; then
         if [ "$statusline" = "1" ] ; then
             echo "# Problem is unsatisfiable, constructing proof object"
 	else
-	    echo "# Cannot determine problem status"
-	    exit 1
+	    statusline=`grep -c 'Watchlist is empty!' $tmpfile2`
+	    if [ "$statusline" = "1" ] ; then
+		echo "# All watchlist clauses generated, constructing derivation"
+	    else
+		echo "# Cannot determine problem status"
+		exit 1
+	    fi
 	fi
     fi
     prooflimit=`expr $timelimit - $searchtime - 1`
