Improved the extract stuff on Geoff's behalf

diff --git a/PROVER/eproof b/PROVER/eproof
--- a/PROVER/eproof
+++ b/PROVER/eproof
@@ -53,7 +53,18 @@ $EXECPATH/eprover $* -l4 -R -o- --pcl-terms-compressed > $tmpfile
 tail -40 $tmpfile > $tmpfile2
 searchtime=`cat $tmpfile2|grep "Total time"|cut -d: -f2|sed -e's/[s ]//g'|cut -d. -f1`
 if [ "$searchtime" ]; then
-    echo "# Problem status determined, constructing proof object"
+    statusline=`grep -c 'No proof found!' $tmpfile`
+    if [ "$statusline" = "1" ] ; then
+        echo "# Problem is satisfiable, generating saturation derivation"
+    else
+	statusline=`grep -c 'Proof found!' $tmpfile`
+        if [ "$statusline" = "1" ] ; then
+            echo "# Problem is unsatisfiable, constructing proof object"
+	else
+	    echo "# Cannot determine problem status"
+	    exit 1
+	fi
+    fi
     prooflimit=`expr $timelimit - $searchtime - 1`
     ulimit -S -t $prooflimit
     if  [ "$outfile" = "" ] ; then
